### PR TITLE
Add document describing correct use of virt-v2v in forklift

### PR DESCRIPTION
**Pull request by rwmjones**
Signed-off-by: Richard W.M. Jones <rjones@redhat.com>

### CODE REVIEW

**Comment by jortel** [comment]
Thank you! @rwmjones

**Comment by jwmatthews** [comment]
Due to the nature of Konveyor changing to align to the [Unified Vision](https://github.com/konveyor/enhancements/tree/master/enhancements/unified_experience), I think it's best we close this PR out.

If you feel strongly otherwise please reopen and add a comment.

**Comment by rwmjones** [comment]
Dare I ask what the "Unified Vision" is?

**Comment by jwmatthews** [comment]
@rwmjones I hope the link helps, working on an update to the Charter as well.  Short summary is we want to align Konveyor to the Application Modernization needs that Tackle has been addressing and move away from the prior concept of Konveyor being a collection of independent projects working in a loosely related problem space. 

From that effort we've rehomed several of the former Konveyor projects.
For example, Forklift is now under https://github.com/kubev2v

**Pull request closed without merging**
